add `std`,`alloc` feature flag to support `no_std` build
nginxinc/ngx-rust pull request #111
Opened 2024-12-26 23:11 UTC by JyJyJcr

### Proposed changes
add features `std`, `alloc` to prepare for `no_std` build support.
- `alloc` feature means memory allocation used. Implementation differs depending on `std` feature:
  - with `std`: use `std` crate components. (e.g. `alloc::string::String`)
  - without `std`: use `alloc` crate components. (e.g. `std::string::String`)
- `std` feature means `std` crate components used. Currently the only difference between `std` and `alloc` is impl of `std::error::Error` (`core::error::Error` is not in Rust 1.79.0), which is not used.

`alloc` is the transitional feature: while it enables `no_std` build, it allows memory allocation using `std::alloc::System` internally. We can gradually replace `alloc` crate components by nginx-based ones.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. 
- [x] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [x] I have added tests (when possible) that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto master
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

2024-12-27 07:15 UTC, bavshin-f5 commented
Thanks!
Looks similar to what I intended to do, I'll take a closer look next week when I'm back from vacation.

One comment: I'd prefer to remove `String` from `nginx-sys` completely instead of introducing the `alloc` feature.
Display impl commit in https://github.com/nginxinc/ngx-rust/pull/113 supposed to be a first step towards that, another step is to rewrite `nginx_sys::add_to_ngx_table` like in https://github.com/bavshin-f5/ngx-rust/commit/ae2ee99039c2163f88944498ea1f59f8a55c75f2, and the last step is to remove remaining redundant conversions.

2024-12-27 10:48 UTC, JyJyJcr commented
Thank you for the advice.
I replaced them by your implementation bavshin-f5@3f054e3026dcce08929dcf7dfe3f46b92c3ecec5, bavshin-f5@ae2ee99039c2163f88944498ea1f59f8a55c75f2  for the moment.
`nginx-sys` is now alloc-free.

2025-01-01 13:28 UTC, bavshin-f5 requested changes
The comments for `Request::headers_in_iterator`/`Request::headers_out_iterator` need to be updated.
***
Please, squash all the fixup commits and clean up the history.
I believe this PR can be reorganized into 3-4 commits with distinct logical changes. For example,
* Replacing `std` with `core` and `alloc`
* Rework of the header iterator
* Removal of the remaining `String` uses
* Feature flags and documentation

2025-01-01 13:28 UTC, bavshin-f5 commented on src/http/module.rs
> +    fn fmt(&self, fmt: &mut core::fmt::Formatter) -> core::fmt::Result {
Consider making this a bit cleaner with `use core::fmt;`.

Same suggestion for `nginx-sys/src/lib.rs`.  I had the change in my local copy, but this PR will likely be merged first.

2025-01-01 16:25 UTC, JyJyJcr commented
Thank you for the reviewing.

I'll fix the points one by one, and after that do squash.

2025-01-01 16:33 UTC, JyJyJcr commented on nginx-sys/src/lib.rs
> +#![cfg_attr(not(test), no_std)]
fixed.

2025-01-01 16:50 UTC, JyJyJcr commented on src/core/string.rs
> +use std::{borrow::Cow, string::String};
Same to https://github.com/nginxinc/ngx-rust/pull/111#discussion_r1900386701.

2025-01-01 16:55 UTC, JyJyJcr commented on src/http/request.rs
> +    __: PhantomData<&'a ()>,
By treating field `h` as slice, the impl will be more rust-style: see b74b11125bbda1f2ac4637e685c714ccf78f0e73

2025-01-01 17:17 UTC, bavshin-f5 commented on src/log.rs
> +}
...right, `alloc` crate is not imported automatically in `std` environment.

I'd suggest to revert the whole set of log.rs changes and make `ngx::log` *temporarily* available only in `std` environment. I'll remove `CString` in another PR.

2025-01-02 13:16 UTC, JyJyJcr commented
chores:
- NGINX part of workflows has been broken in some point. It seems unrelated to this PR.
- I've added thumbs up emoji to mark as completed (in my perspective), avoiding annoying you by many short messages.

2025-01-02 14:13 UTC, bavshin-f5 commented
>     * NGINX part of workflows has been broken in some point. It seems unrelated to this PR.

Worker processes crash when running awssig example code:

> `#          got: '2025/01/02 13:13:30 [alert] 5687#5687: worker process 5688 exited on signal 6 (core dumped)'`

That's the only example that uses the header iterators, the crash is likely in `Iterator::next` implementation.

2025-01-02 14:46 UTC, bavshin-f5 requested changes

2025-01-02 14:46 UTC, bavshin-f5 commented on src/http/request.rs
> +    }
`raw.nelts` can be 0. In this case, `raw.elts` will be NULL or uninitialized, violating safety requirements of `slice::from_raw_parts`

2025-01-02 14:46 UTC, bavshin-f5 commented on src/http/request.rs
> +        let header = &part.arr[self.i];
You assume that the `ngx_list_part_t` always contains at least one element, but that's not the case if the header list is empty.

2025-01-02 15:26 UTC, JyJyJcr commented on src/http/request.rs
> +        let header = &part.arr[self.i];
Is there possibility that empty list parts are chained? if so, I'll fix this with while.

2025-01-02 16:33 UTC, bavshin-f5 commented on src/http/request.rs
> +        let header = &part.arr[self.i];
`ngx_list_t` does not support item removal; if a new list part is allocated it will always contain at least one element.

2025-01-02 16:45 UTC, JyJyJcr commented on src/http/request.rs
> +        let header = &part.arr[self.i];
Now test failure is fixed, thank you for the quick advices!

2025-01-02 18:34 UTC, JyJyJcr commented
commit squashed.

2025-01-02 21:03 UTC, bavshin-f5 requested changes
Almost ready, just a couple more issues.

98cb85de and 0174f10e fail to build. Please, consider reordering the commits as shown below to make each commit buildable:
1. fix: refactor `NgxListIterator` to remove `String` usage
1. fix: replace other `String` usage by bavshin-f5's impl
    (`use alloc::string::ToString` addition in the test code should be moved to the `no_std` commit)
1. chore: add Cargo features
1. fix: replace `std` to `core` and add config out

2025-01-03 06:13 UTC, bavshin-f5 commented on nginx-sys/src/lib.rs
> +        // The implementation is similar to an inlined `String::from_utf8_lossy`, with two
This change is in the wrong commit.

Everything else looks good. Thanks a lot for your work!

2025-01-03 06:24 UTC, JyJyJcr commented on nginx-sys/src/lib.rs
> +        // The implementation is similar to an inlined `String::from_utf8_lossy`, with two
Thank you too, for reviewing my incomplete commits!

2025-01-03 06:48 UTC, bavshin-f5 approved these changes

2025-01-03 06:49 UTC, merged